"""Generate Foundry test files (.t.sol) from parsed pData for local debugging."""

from __future__ import annotations

import datetime
import os
from pathlib import Path

from .constants import ChainConfig
from .parser import ParsedPData

TEMPLATE = '''// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "forge-std/Test.sol";

/// @notice Auto-generated by atlas-pdata-debugger from {source_file}
/// Chain: {chain_name} ({chain_id})
/// Auction: {auction_id}
/// Oracle time: {oracle_time}
/// Deadline: {deadline}
/// Solver: {solver_addr}
/// Bid: {bid_display}
///
/// Run:
///   forge test --match-path {match_path} --match-test test_replay -vvvv \\
///     --fork-url {rpc_hint} \\
///     --fork-block-number {fork_block}
contract PDataReplay_{test_id} is Test {{

    function test_replay() public {{
        vm.txGasPrice({gas_price});
{mock_calls}
        _setupLabels();
        address simulator = {simulator};
        bytes memory pData = _pData();

        console.log("=== simSolverCall replay ===");
        console.log("block.number (L1 on Arb fork):", block.number);
        console.log("SafeBlockNumber (mocked L2):", uint256({fork_block}));

        (bool ok, bytes memory ret) = simulator.call(pData);

        if (ret.length >= 96) {{
            (bool success, uint8 simResult, uint256 outcome) = abi.decode(ret, (bool, uint8, uint256));
            console.log("success:", success);
            console.log("simResult:", simResult);
            _decodeSimResult(simResult);
            console.log("outcome:", outcome);
            _decodeOutcome(outcome);
        }} else {{
            console.log("Call reverted, ok:", ok);
            console.logBytes(ret);
        }}
    }}

    function _decodeSimResult(uint8 r) internal pure {{
        if (r == 0) console.log("  simResult -> Unknown");
        else if (r == 1) console.log("  simResult -> VerificationSimFail");
        else if (r == 2) console.log("  simResult -> PreOpsSimFail");
        else if (r == 3) console.log("  simResult -> UserOpSimFail");
        else if (r == 4) console.log("  simResult -> SolverSimFail");
        else if (r == 5) console.log("  simResult -> AllocateValueSimFail");
        else if (r == 6) console.log("  simResult -> SimulationPassed");
    }}

    function _decodeOutcome(uint256 o) internal pure {{
        if (o == 0) {{ console.log("  outcome  -> Passed"); return; }}
        if (o & (1 << 0)  != 0) console.log("  outcome  -> InvalidSignature");
        if (o & (1 << 1)  != 0) console.log("  outcome  -> InvalidUserHash");
        if (o & (1 << 2)  != 0) console.log("  outcome  -> DeadlinePassedAlt");
        if (o & (1 << 3)  != 0) console.log("  outcome  -> GasPriceBelowUsersAlt");
        if (o & (1 << 4)  != 0) console.log("  outcome  -> InvalidTo");
        if (o & (1 << 5)  != 0) console.log("  outcome  -> UserOutOfGas");
        if (o & (1 << 6)  != 0) console.log("  outcome  -> AlteredControl");
        if (o & (1 << 7)  != 0) console.log("  outcome  -> AltOpHashMismatch");
        if (o & (1 << 8)  != 0) console.log("  outcome  -> DeadlinePassed");
        if (o & (1 << 9)  != 0) console.log("  outcome  -> GasPriceOverCap");
        if (o & (1 << 10) != 0) console.log("  outcome  -> InvalidSolver");
        if (o & (1 << 11) != 0) console.log("  outcome  -> InvalidBidToken");
        if (o & (1 << 12) != 0) console.log("  outcome  -> PerBlockLimit (solver already accessed this block)");
        if (o & (1 << 13) != 0) console.log("  outcome  -> InsufficientEscrow");
        if (o & (1 << 14) != 0) console.log("  outcome  -> GasPriceBelowUsers");
        if (o & (1 << 15) != 0) console.log("  outcome  -> CallValueTooHigh");
        if (o & (1 << 16) != 0) console.log("  outcome  -> PreSolverFailed");
        if (o & (1 << 17) != 0) console.log("  outcome  -> SolverOpReverted");
        if (o & (1 << 18) != 0) console.log("  outcome  -> PostSolverFailed");
        if (o & (1 << 19) != 0) console.log("  outcome  -> BidNotPaid");
        if (o & (1 << 20) != 0) console.log("  outcome  -> InvertedBidExceedsCeiling");
        if (o & (1 << 21) != 0) console.log("  outcome  -> BalanceNotReconciled");
        if (o & (1 << 22) != 0) console.log("  outcome  -> CallbackNotCalled");
        if (o & (1 << 23) != 0) console.log("  outcome  -> EVMError");
    }}

    function _setupLabels() internal {{
{label_calls}
    }}

    function _pData() internal pure returns (bytes memory) {{
        return hex"{pdata_hex}";
    }}
}}
'''

ARB_MOCK_BLOCK = '''
        vm.mockCall(
            address(0x6C),
            abi.encodeWithSignature("getPricesInArbGas()"),
            abi.encode(uint256(0), uint256(16), uint256(0))
        );
        // NOTE: On Arbitrum, block.number inside Foundry forks returns the L1
        // block, but SafeBlockNumber.get() calls arbBlockNumber() which returns
        // the L2 block. We mock it to the L2 fork block so per-block-limit and
        // similar checks compare apples to apples against on-chain state.
        vm.mockCall(
            address(0x64),
            abi.encodeWithSignature("arbBlockNumber()"),
            abi.encode(uint256({fork_block}))
        );'''


# Per-chain wrapped-native token (WETH / WBNB) addresses. Used purely for vm.label
# so that traces show "[WETH]" instead of the raw address when these contracts
# are touched.
_CHAIN_WRAPPED_NATIVE: dict[int, tuple[str, str]] = {
    1: ("0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2", "WETH"),
    42161: ("0x82aF49447D8a07e3bd95BD0d56f35241523fBab1", "WETH"),
    8453: ("0x4200000000000000000000000000000000000006", "WETH"),
    56: ("0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c", "WBNB"),
}

_ZERO_ADDR = "0x0000000000000000000000000000000000000000"


def _sol_addr_literal(addr: str) -> str:
    """Render an address as a Solidity literal that always compiles.

    Solidity 0.8.x treats any 39-41 digit hex literal as an address candidate
    and enforces the EIP-55 checksum on it — so a lowercased pData address
    like `0x9d8a4c...` fails to compile. We sidestep that by zero-padding the
    hex to 42 digits (outside the address-candidate range) and casting via
    `address(uint160(...))`. Computing a real checksum would require a Keccak
    implementation, which we deliberately avoid as a dependency.
    """
    hex_part = addr.strip()
    if hex_part.startswith("0x") or hex_part.startswith("0X"):
        hex_part = hex_part[2:]
    return f"address(uint160(0x00{hex_part.lower()}))"


def _build_labels(
    pdata: ParsedPData,
    chain: ChainConfig,
    feed_description: str | None = None,
) -> str:
    """Build a block of `vm.label(addr, "name")` calls for known addresses.

    Foundry's verbose trace renders `vm.label`-ed addresses with their friendly
    name in `-vvvv` output, which makes both human and AI inspection of the
    trace dramatically easier. We register every address we already know from
    the pData decode + chain config + RPC-resolved feed description.

    Returns a string with one `vm.label(...)` call per line, each indented 8
    spaces to match the body of `_setupLabels()`. Returns an empty
    placeholder line if no labels apply (so the function body stays valid).
    """
    seen: set[str] = set()
    pairs: list[tuple[str, str]] = []

    def add(addr: str | None, name: str) -> None:
        if not addr:
            return
        addr = addr.strip()
        if not addr.startswith("0x") or len(addr) != 42:
            return
        key = addr.lower()
        if key == _ZERO_ADDR or key in seen:
            return
        seen.add(key)
        pairs.append((addr, name))

    add(pdata.simulator or chain.simulator, "Simulator")
    add(chain.atlas, "Atlas")

    wrapped = _CHAIN_WRAPPED_NATIVE.get(chain.chain_id)
    if wrapped:
        add(wrapped[0], wrapped[1])

    if pdata.user_op:
        uo = pdata.user_op
        add(uo.from_addr, "UserEOA")
        add(uo.to_addr, "Atlas")
        # DAppControl is the more informative label for trace inspection (it's
        # what actually handles pre/post-op hooks), so register it before
        # `dapp` — for SVR feeds the two addresses are typically identical.
        add(uo.control, "DAppControl")
        add(uo.dapp, "DApp")
        add(uo.session_key, "SessionKey")

    if pdata.solver_op:
        so = pdata.solver_op
        add(so.control, "DAppControl")
        add(so.from_addr, "SolverEOA")
        add(so.solver, "Solver")
        add(so.bid_token, "BidToken")

    if pdata.dapp_op:
        do = pdata.dapp_op
        add(do.bundler, "Bundler")
        add(do.from_addr, "DAppOpSigner")

    if pdata.oracle_report:
        rep = pdata.oracle_report
        if rep.atlas_wrapper:
            add(rep.atlas_wrapper, "ChainlinkAtlasWrapper")
        if rep.base_feed:
            label = f"{feed_description} Feed" if feed_description else "ChainlinkBaseFeed"
            add(rep.base_feed, label)

    if not pairs:
        return "        // (no known addresses to label)"

    lines: list[str] = []
    for addr, name in pairs:
        safe_name = name.replace('"', '\\"')
        lines.append(f'        vm.label({_sol_addr_literal(addr)}, "{safe_name}");')
    return "\n".join(lines)


def generate_test(
    pdata: ParsedPData,
    chain: ChainConfig,
    oracle_block: int | None,
    source_file: str = "",
    fork_block: int | None = None,
    feed_description: str | None = None,
    match_path: str | None = None,
) -> str:
    """Generate a complete Solidity test file from parsed pData.

    `fork_block` (when provided) is used as the explicit `--fork-block-number`
    in the generated test header. If not provided, falls back to `oracle_block`
    or `deadline - 100`.

    `feed_description` (when provided, e.g. "BTC / USD") is woven into the
    `vm.label` call for the base Chainlink feed so traces show the asset pair.

    `match_path` (when provided, e.g. "test/pdata0505.t.sol") is embedded into
    the doc-comment `Run:` example so the printed `forge test` command targets
    just this file — otherwise forge would also pick up other `.t.sol` files
    in the test/ directory that happen to define a `test_replay` function.
    """
    # Determine identifiers
    auction_id = pdata.auction_id or "unknown"
    test_id = auction_id.split("-")[0] if auction_id != "unknown" else "test"

    solver_addr = ""
    bid_display = ""
    if pdata.solver_op:
        solver_addr = pdata.solver_op.solver
        bid_eth = pdata.solver_op.bid_amount / 1e18
        bid_display = f"{bid_eth:.10f} ETH ({pdata.solver_op.bid_amount} wei)"

    deadline = pdata.user_op.deadline if pdata.user_op else 0
    gas_price = pdata.gas_fee_cap or (pdata.user_op.max_fee_per_gas if pdata.user_op else 0)

    oracle_time = ""
    if pdata.oracle_timestamp:
        dt = datetime.datetime.utcfromtimestamp(pdata.oracle_timestamp)
        oracle_time = dt.strftime("%Y-%m-%d %H:%M:%S UTC")

    if fork_block is None:
        fork_block = oracle_block or (deadline - 100)

    simulator = pdata.simulator or chain.simulator

    # RPC hint
    rpc_hint = chain.rpcs[0] if chain.rpcs else "<RPC_URL>"

    mock_calls = ""
    if chain.arb_precompiles:
        mock_calls = ARB_MOCK_BLOCK.format(fork_block=fork_block)

    label_calls = _build_labels(pdata, chain, feed_description=feed_description)

    pdata_hex = pdata.raw_hex

    if match_path is None:
        match_path = "test/<this_file>.t.sol"

    return TEMPLATE.format(
        source_file=os.path.basename(source_file),
        chain_name=chain.name,
        chain_id=chain.chain_id,
        auction_id=auction_id,
        oracle_time=oracle_time,
        deadline=deadline,
        solver_addr=solver_addr,
        bid_display=bid_display,
        gas_price=gas_price,
        rpc_hint=rpc_hint,
        fork_block=fork_block,
        test_id=test_id,
        simulator=simulator,
        mock_calls=mock_calls,
        label_calls=label_calls,
        match_path=match_path,
        pdata_hex=pdata_hex,
    )


def write_test(
    pdata: ParsedPData,
    chain: ChainConfig,
    oracle_block: int | None,
    output_path: str,
    source_file: str = "",
    fork_block: int | None = None,
    feed_description: str | None = None,
) -> str:
    """Generate and write a Foundry test file. Returns the output path."""
    path = Path(output_path)

    # Derive a forge-friendly match path (e.g. "test/pdata0505.t.sol") so the
    # generated `Run:` example only executes this one file rather than every
    # other `.t.sol` lingering in the test/ directory.
    match_path = f"{path.parent.name}/{path.name}" if path.parent.name else path.name

    content = generate_test(
        pdata,
        chain,
        oracle_block,
        source_file,
        fork_block=fork_block,
        feed_description=feed_description,
        match_path=match_path,
    )

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)

    return str(path)
